
import { Product } from './type';

export const products: Product[] = [
  {
    id: 1,
    title: "Stylish T-Shirt",
    image: ["/arrival-img1.png","/arrival-img2.png"],
    slug: "stylish-t-shirt",
    price: 1200,
    category: "Clothing",
    description: "A high-quality cotton t-shirt with a stylish design.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 10,
  },
  {
    id: 2,
    title: "Leather Wallet",
    image: ["/arrival-img3.png","/arrival-img4.png"],
    slug: "leather-wallet",
    price: 1500, 
    category: "Accessories",
    description: "A premium leather wallet with multiple compartments.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 0,
  },
  {
    id: 3,
    title: "Running Shoes",
    image: ["/sell1.png","/sell2.png"],
    slug: "running-shoes",
    price: 3000,
    category: "Footwear",
    description: "Comfortable and durable running shoes for daily wear.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 15,
  },
  {
    id: 4,
    title: "Smart Watch",
    image: ["/sell3.png","/arrival-img4.png"],
    slug: "smart-watch",
    price: 5000,
    category: "Electronics",
    description: "A sleek smart watch with fitness tracking features.",
    size: ["S", "M", "L", "XL"],
    color: ["red", "blue", "black"],
    qty: 1,
    discount: 0,
  },
];
